USE [FoodLovers]
CREATE TABLE dbo.BranchProduct
	(
	BranchID int NOT NULL,
	ProductID int NOT NULL
	)
GO
ALTER TABLE dbo.BranchProduct ADD CONSTRAINT
	PK_BranchProduct PRIMARY KEY CLUSTERED 
	(
	BranchID, ProductID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO